import { z } from "zod";

/** A single quiz question, generated by AI */
export interface QuizQuestion {
  question: string;
  answer: string;
}

/** AI evaluation of a learner's answer */
export interface AnswerEvaluation {
  /** Score from AI evaluation */
  score: "correct" | "partial" | "missed";
  /** Explanation of what was correct and what was missed */
  explanation: string;
}

/** Self-rating a learner picks after answer reveal (deprecated — replaced by AI evaluation) */
export type SelfRating = "got-it" | "close" | "missed";

/** In-memory state of an active quiz session */
export interface QuizSession {
  topic: string;
  questions: QuizQuestion[];
  currentIndex: number;
  ratings: Map<number, SelfRating>;
  learnerAnswers: Map<number, string>;
}

/** Status of the quiz flow */
export type QuizStatus =
  | "idle"
  | "generating"
  | "answering"
  | "evaluating"
  | "revealing"
  | "summary"
  | "error";

/** Zod schema for quiz_sessions DB rows */
export const QuizRecordSchema = z.object({
  id: z.string(),
  vault_id: z.string(),
  course_id: z.string().nullable(),
  topic: z.string(),
  questions: z.string(),
  created_at: z.string(),
});

export type QuizRecord = z.infer<typeof QuizRecordSchema>;

/** Input for inserting a quiz session record */
export interface QuizSessionInsert {
  id: string;
  vaultId: string;
  courseId: string | null;
  topic: string;
  questions: string; // JSON string of QuizQuestion[]
}

/** Result of spawning a missed-item card */
export interface SpawnResult {
  question: string;
  success: boolean;
  cardId?: string;
  error?: string;
}
